version: '3.8'

services:
  mysql:
    image: mysql:8.0.25
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo_springboot_quartz
      MYSQL_USER: springboot_quartz
      MYSQL_PASSWORD: springboot_quartz
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_net

volumes:
  mysql_data:

networks:
  mysql_net:
    driver: bridge
